import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ImageProvider } from '@/context/imageContext';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} bg-neutral-800 text-white antialiased`}>
                <ImageProvider>
                    {children}
                    <footer className='fixed text-xs opacity-50 bottom-2 inset-x-0 text-center -z-2'>
                        Created by{' '}
                        <a
                            href='https://github.com/zanuaraznan'
                            rel='noopener noreferrer'
                            referrerPolicy='no-referrer'
                            target='_blank'
                            className='font-medium'>
                            ZanuarRasyidin
                        </a>
                    </footer>
                </ImageProvider>
            </body>
        </html>
    );
}
